In [1]:
import pandas as pd
import numpy as ny

In [8]:
# header=0 means that the headers for the variable names are to be found in the first row (note that 0 means the first row in Python)
# sep="," means that "," is used as the separator between the values. This is because we are using the file type .csv (comma separated values)

df =pd.read_csv("bestsellers with categories.csv", header=0 ,sep=",")

In [11]:
df

,Name,Author,User Rating,Reviews,Price,Year,Genre
0,10-Day Green Smoothie Cleanse,JJ Smith,4.7,17350,8,2016,Non Fiction
1,11/22/63: A Novel,Stephen King,4.6,2052,22,2011,Fiction
2,12 Rules for Life: An Antidote to Chaos,Jordan B. Peterson,4.7,18979,15,2018,Non Fiction
3,1984 (Signet Classics),George Orwell,4.7,21424,6,2017,Fiction
4,"5,000 Awesome Facts (About Everything!) (Natio...",National Geographic Kids,4.8,7665,12,2019,Non Fiction
...,...,...,...,...,...,...,...
545,Wrecking Ball (Diary of a Wimpy Kid Book 14),Jeff Kinney,4.9,9413,8,2019,Fiction
546,You Are a Badass: How to Stop Doubting Your Gr...,Jen Sincero,4.7,14331,8,2016,Non Fiction
547,You Are a Badass: How to Stop Doubting Your Gr...,Jen Sincero,4.7,14331,8,2017,Non Fiction
548,You Are a Badass: How to Stop Doubting Your Gr...,Jen Sincero,4.7,14331,8,2018,Non Fiction
549,You Are a Badass: How to Stop Doubting Your Gr...,Jen Sincero,4.7,14331,8,2019,Non Fiction

In [9]:
df_original = df.copy()

In [18]:
# df.copy()

In [19]:
# We can use the dropna() function to remove the NaNs. axis=0 means that we want to remove all rows that have a NaN value:
# 
# Check for any missing values in the DataFrame
df.isnull().values.any()

np.False_

In [20]:
# View the count of nulls per column

print(df.isnull().sum())

Name           0
Author         0
User Rating    0
Reviews        0
Price          0
Year           0
Genre          0
dtype: int64

In [21]:
# We can use the dropna() function to remove the NaNs. axis=0 means that we want to remove all rows that have a NaN value:

df.dropna(axis=0,inplace=True)

print(df)

                                                  Name  \
0                        10-Day Green Smoothie Cleanse
1                                    11/22/63: A Novel
2              12 Rules for Life: An Antidote to Chaos
3                               1984 (Signet Classics)
4    5,000 Awesome Facts (About Everything!) (Natio...
..                                                 ...
545       Wrecking Ball (Diary of a Wimpy Kid Book 14)
546  You Are a Badass: How to Stop Doubting Your Gr...
547  You Are a Badass: How to Stop Doubting Your Gr...
548  You Are a Badass: How to Stop Doubting Your Gr...
549  You Are a Badass: How to Stop Doubting Your Gr...

                       Author  User Rating  Reviews  Price  Year        Genre
0                    JJ Smith          4.7    17350      8  2016  Non Fiction
1                Stephen King          4.6     2052     22  2011      Fiction
2          Jordan B. Peterson          4.7    18979     15  2018  Non Fiction
3               George Orwell          4.7    21424      6  2017      Fiction
4    National Geographic Kids          4.8     7665     12  2019  Non Fiction
..                        ...          ...      ...    ...   ...          ...
545               Jeff Kinney          4.9     9413      8  2019      Fiction
546               Jen Sincero          4.7    14331      8  2016  Non Fiction
547               Jen Sincero          4.7    14331      8  2017  Non Fiction
548               Jen Sincero          4.7    14331      8  2018  Non Fiction
549               Jen Sincero          4.7    14331      8  2019  Non Fiction

[550 rows x 7 columns]

In [22]:
df

,Name,Author,User Rating,Reviews,Price,Year,Genre
0,10-Day Green Smoothie Cleanse,JJ Smith,4.7,17350,8,2016,Non Fiction
1,11/22/63: A Novel,Stephen King,4.6,2052,22,2011,Fiction
2,12 Rules for Life: An Antidote to Chaos,Jordan B. Peterson,4.7,18979,15,2018,Non Fiction
3,1984 (Signet Classics),George Orwell,4.7,21424,6,2017,Fiction
4,"5,000 Awesome Facts (About Everything!) (Natio...",National Geographic Kids,4.8,7665,12,2019,Non Fiction
...,...,...,...,...,...,...,...
545,Wrecking Ball (Diary of a Wimpy Kid Book 14),Jeff Kinney,4.9,9413,8,2019,Fiction
546,You Are a Badass: How to Stop Doubting Your Gr...,Jen Sincero,4.7,14331,8,2016,Non Fiction
547,You Are a Badass: How to Stop Doubting Your Gr...,Jen Sincero,4.7,14331,8,2017,Non Fiction
548,You Are a Badass: How to Stop Doubting Your Gr...,Jen Sincero,4.7,14331,8,2018,Non Fiction
549,You Are a Badass: How to Stop Doubting Your Gr...,Jen Sincero,4.7,14331,8,2019,Non Fiction

In [23]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 550 entries, 0 to 549
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Name         550 non-null    object
 1   Author       550 non-null    object
 2   User Rating  550 non-null    float64
 3   Reviews      550 non-null    int64
 4   Price        550 non-null    int64
 5   Year         550 non-null    int64
 6   Genre        550 non-null    object
dtypes: float64(1), int64(3), object(3)
memory usage: 30.2+ KB

In [28]:
# df["Name"]=df["Name"].astype(str)
df.head()

,Name,Author,User Rating,Reviews,Price,Year,Genre
0,10-Day Green Smoothie Cleanse,JJ Smith,4.7,17350,8,2016,Non Fiction
1,11/22/63: A Novel,Stephen King,4.6,2052,22,2011,Fiction
2,12 Rules for Life: An Antidote to Chaos,Jordan B. Peterson,4.7,18979,15,2018,Non Fiction
3,1984 (Signet Classics),George Orwell,4.7,21424,6,2017,Fiction
4,"5,000 Awesome Facts (About Everything!) (Natio...",National Geographic Kids,4.8,7665,12,2019,Non Fiction

In [29]:
df.shape

(550, 7)

In [30]:
df.columns

Index(['Name', 'Author', 'User Rating', 'Reviews', 'Price', 'Year', 'Genre'], dtype='object')

In [31]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 550 entries, 0 to 549
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Name         550 non-null    object
 1   Author       550 non-null    object
 2   User Rating  550 non-null    float64
 3   Reviews      550 non-null    int64
 4   Price        550 non-null    int64
 5   Year         550 non-null    int64
 6   Genre        550 non-null    object
dtypes: float64(1), int64(3), object(3)
memory usage: 30.2+ KB

In [32]:
df.describe()

       User Rating       Reviews       Price         Year
count   550.000000    550.000000  550.000000   550.000000
mean      4.618364  11953.281818   13.100000  2014.000000
std       0.226980  11731.132017   10.842262     3.165156
min       3.300000     37.000000    0.000000  2009.000000
25%       4.500000   4058.000000    7.000000  2011.000000
50%       4.700000   8580.000000   11.000000  2014.000000
75%       4.800000  17253.250000   16.000000  2017.000000
max       4.900000  87841.000000  105.000000  2019.000000

In [33]:
# check for duplicates and drop them

df.duplicated().sum()

np.int64(0)

In [34]:
df = df.drop_duplicates()

In [35]:
# create needed columns 
df["Revenue"] = df["Price"] * df["Reviews"]

In [36]:
df

,Name,Author,User Rating,Reviews,Price,Year,Genre,Revenue
0,10-Day Green Smoothie Cleanse,JJ Smith,4.7,17350,8,2016,Non Fiction,138800
1,11/22/63: A Novel,Stephen King,4.6,2052,22,2011,Fiction,45144
2,12 Rules for Life: An Antidote to Chaos,Jordan B. Peterson,4.7,18979,15,2018,Non Fiction,284685
3,1984 (Signet Classics),George Orwell,4.7,21424,6,2017,Fiction,128544
4,"5,000 Awesome Facts (About Everything!) (Natio...",National Geographic Kids,4.8,7665,12,2019,Non Fiction,91980
...,...,...,...,...,...,...,...,...
545,Wrecking Ball (Diary of a Wimpy Kid Book 14),Jeff Kinney,4.9,9413,8,2019,Fiction,75304
546,You Are a Badass: How to Stop Doubting Your Gr...,Jen Sincero,4.7,14331,8,2016,Non Fiction,114648
547,You Are a Badass: How to Stop Doubting Your Gr...,Jen Sincero,4.7,14331,8,2017,Non Fiction,114648
548,You Are a Badass: How to Stop Doubting Your Gr...,Jen Sincero,4.7,14331,8,2018,Non Fiction,114648
549,You Are a Badass: How to Stop Doubting Your Gr...,Jen Sincero,4.7,14331,8,2019,Non Fiction,114648

In [37]:
df["Price Category"] = pd.cut(df["Price"],
                             bins=[0,10,20,50,100],
                             labels=["Cheap","Mid","High","Luxury"])

In [38]:
df

,Name,Author,User Rating,Reviews,Price,Year,Genre,Revenue,Price Category
0,10-Day Green Smoothie Cleanse,JJ Smith,4.7,17350,8,2016,Non Fiction,138800,Cheap
1,11/22/63: A Novel,Stephen King,4.6,2052,22,2011,Fiction,45144,High
2,12 Rules for Life: An Antidote to Chaos,Jordan B. Peterson,4.7,18979,15,2018,Non Fiction,284685,Mid
3,1984 (Signet Classics),George Orwell,4.7,21424,6,2017,Fiction,128544,Cheap
4,"5,000 Awesome Facts (About Everything!) (Natio...",National Geographic Kids,4.8,7665,12,2019,Non Fiction,91980,Mid
...,...,...,...,...,...,...,...,...,...
545,Wrecking Ball (Diary of a Wimpy Kid Book 14),Jeff Kinney,4.9,9413,8,2019,Fiction,75304,Cheap
546,You Are a Badass: How to Stop Doubting Your Gr...,Jen Sincero,4.7,14331,8,2016,Non Fiction,114648,Cheap
547,You Are a Badass: How to Stop Doubting Your Gr...,Jen Sincero,4.7,14331,8,2017,Non Fiction,114648,Cheap
548,You Are a Badass: How to Stop Doubting Your Gr...,Jen Sincero,4.7,14331,8,2018,Non Fiction,114648,Cheap
549,You Are a Badass: How to Stop Doubting Your Gr...,Jen Sincero,4.7,14331,8,2019,Non Fiction,114648,Cheap

In [39]:
df.isnull().sum()

Name               0
Author             0
User Rating        0
Reviews            0
Price              0
Year               0
Genre              0
Revenue            0
Price Category    14
dtype: int64

In [40]:
df.duplicated().sum()

np.int64(0)

In [41]:
df.describe()

       User Rating       Reviews       Price         Year       Revenue
count   550.000000    550.000000  550.000000   550.000000  5.500000e+02
mean      4.618364  11953.281818   13.100000  2014.000000  1.427262e+05
std       0.226980  11731.132017   10.842262     3.165156  1.723369e+05
min       3.300000     37.000000    0.000000  2009.000000  0.000000e+00
25%       4.500000   4058.000000    7.000000  2011.000000  4.418500e+04
50%       4.700000   8580.000000   11.000000  2014.000000  8.578400e+04
75%       4.800000  17253.250000   16.000000  2017.000000  1.746720e+05
max       4.900000  87841.000000  105.000000  2019.000000  1.430028e+06

In [42]:
# popularity score (simple version)
df["Popularity"] = df["User Rating"] * df["Reviews"]

In [45]:
# sort by reviews from the most popular
df.sort_values(by="Reviews", ascending =False).reset_index(drop=True)

,Name,Author,User Rating,Reviews,Price,Year,Genre,Revenue,Price Category,Popularity
0,Where the Crawdads Sing,Delia Owens,4.8,87841,15,2019,Fiction,1317615,Mid,421636.8
1,The Girl on the Train,Paula Hawkins,4.1,79446,18,2015,Fiction,1430028,Mid,325728.6
2,The Girl on the Train,Paula Hawkins,4.1,79446,7,2016,Fiction,556122,Cheap,325728.6
3,Becoming,Michelle Obama,4.8,61133,11,2018,Non Fiction,672463,Mid,293438.4
4,Becoming,Michelle Obama,4.8,61133,11,2019,Non Fiction,672463,Mid,293438.4
...,...,...,...,...,...,...,...,...,...,...
545,The Daily Show with Jon Stewart Presents Earth...,Jon Stewart,4.4,440,11,2010,Non Fiction,4840,Mid,1936.0
546,True Compass: A Memoir,Edward M. Kennedy,4.5,438,15,2009,Non Fiction,6570,Mid,1971.0
547,George Washington's Sacred Fire,Peter A. Lillback,4.5,408,20,2010,Non Fiction,8160,Mid,1836.0
548,Soul Healing Miracles: Ancient and New Sacred ...,Zhi Gang Sha,4.6,220,17,2013,Non Fiction,3740,Mid,1012.0
549,Divine Soul Mind Body Healing and Transmission...,Zhi Gang Sha,4.6,37,6,2009,Non Fiction,222,Cheap,170.2

In [46]:
df.groupby("Genre")["Reviews"].sum()

Genre
Fiction        3764110
Non Fiction    2810195
Name: Reviews, dtype: int64

In [47]:
df.groupby("Author")["Reviews"].sum()

Author
Abraham Verghese               9732
Adam Gasiewski                 3113
Adam Mansbach                  9568
Adir Levy                      8170
Admiral William H. McRaven    10199
                              ...
Walter Isaacson               18668
William Davis                 14994
William P. Young              39440
Wizards RPG Team              50970
Zhi Gang Sha                    257
Name: Reviews, Length: 248, dtype: int64

In [53]:
df.groupby(["Author","User Rating"])["Reviews"].mean().reset_index().sort_values(by="User Rating", ascending=False)

                    Author  User Rating  Reviews
150            Jeff Kinney          4.9   9413.0
49             Chip Gaines          4.9   7861.0
99              Eric Carle          4.9  19546.0
98   Emily Winfield Martin          4.9   8842.0
219             Pete Souza          4.9   3192.0
..                     ...          ...      ...
291          Veronica Roth          3.9   6310.0
83             Donna Tartt          3.9  33844.0
90               E L James          3.8  47265.0
124             Harper Lee          3.6  14982.0
137           J.K. Rowling          3.3   9372.0

[301 rows x 3 columns]

In [58]:
# using aggregations to pass math functions

df.groupby(["Author","User Rating"])["Reviews"].agg(["mean","max","median"]).reset_index().sort_values(by="max", ascending=False)

                Author  User Rating     mean    max   median
80         Delia Owens          4.8  87841.0  87841  87841.0
216      Paula Hawkins          4.1  79446.0  79446  79446.0
204     Michelle Obama          4.8  61133.0  61133  61133.0
119      Gillian Flynn          4.0  57271.0  57271  57271.0
159         John Green          4.7  50482.0  50482  50482.0
..                 ...          ...      ...    ...      ...
176   Larry Schweikart          4.6    460.0    460    460.0
165        Jon Stewart          4.4    440.0    440    440.0
95   Edward M. Kennedy          4.5    438.0    438    438.0
220  Peter A. Lillback          4.5    408.0    408    408.0
300       Zhi Gang Sha          4.6    128.5    220    128.5

[301 rows x 5 columns]